#!/bin/csh -f 

cd /iitm1/cccr/guest9/swathi/iitm/mpi_llnl_codes
#source /usr/share/Modules/init/tcsh
#module purge
#module load netcdf/4.2.1
#module load intel-cluster-studio-2013
module list


set OUTPUT_PATH = /iitm1/cccr/guest9/swathi/iitm/mpi_llnl_codes # change this to where you want the output to go
set MPPNCCOMBINE = "/iitm1/cccr/guest9/iitm-esm/src/postproc/mppncombine/mppnccombine"
set NPES = 16 # Try this on more number of PE's
set WORKDIR = $OUTPUT_PATH/tempdir
cd $WORKDIR
# Change what follows to your system template.
#
/bin/rm heat.nc* 
# Change what follows to your system template.
#

cat > heat_eqn_nml <<EOF
&heat_eqn_nml
 ni = 1000,
 nj = 1000,
 del_t = 1.0e-16,
 nt_steps = 5,
 io_int=5,
 domain_layout=4,4
/
EOF

#mpiexec_mpt -np $NPES  ./a.out > results || set BOMB = 1
#mpiexec_mpt -np $NPES -tv ./a.out || set BOMB = 1
mpirun  -np $NPES a.out > results || set BOMB = 1
#ddt --start mpirun -np $NPES ./a.out > results || set BOMB = 1
cp results $OUTPUT_PATH

#if ($BOMB == 0) then
# set diag_list = (`/bin/ls *nc.0000`)    
# echo "diag_list=" $diag_list
# foreach file ($diag_list)
#   set file_nam = $file:r
  # $MPPNCCOMBINE  $file_nam
#   mv $file_nam $OUTPUT_PATH
#   /bin/rm $file_nam* 
# end
#endif

exit

