#! /bin/csh -f
set echo on
# 05/10/10..For tutorial purposes..using shared code from FMS-SWM
cd /lustre/scratch/swathi/for_nansen

set OUTPUT_PATH = /lustre/scratch/swathi/for_nansen # change this to where you want the output to go
set MPPNCCOMBINE = /lustre/scratch/swathi/shallow_water_zhi_nansen/shallow_water/bin/mppnccombine.ice #  
set NPES = 12 # Try this on more number of PE's
set WORKDIR = $OUTPUT_PATH/tempdir_test_mpp
set FMS_UTILS = /lustre/scratch/swathi/shallow_water_zhi_nansen/shallow_water/src/shared # Change this to where you have the shared FMS code 
#set FMS_UTILITIES = "$FMS_UTILS/utilities $FMS_UTILS/time_manager $FMS_UTILS/mpp $FMS_UTILS/diag_manager $FMS_UTILS/fpe $FMS_UTILS/clocks $FMS_UTILS/memutils"
set FMS_UTILITIES = "$FMS_UTILS/platform $FMS_UTILS/constants $FMS_UTILS/fms $FMS_UTILS/time_manager $FMS_UTILS/mpp $FMS_UTILS/diag_manager  $FMS_UTILS/memutils"
set MKMF         = /lustre/scratch/swathi/shallow_water_zhi_nansen/shallow_water/bin/mkmf 
set FORT_FILE =  ''
cd $WORKDIR
/bin/rm *.nc 
# Change what follows to your system template.
cat > template <<EOF
  FC       = ifort -what
  LD       = ifort
  FFLAGS =  -I/usr/local/include -I/lustre/applications/netcdf/netcdf-3.6.3/include -Duse_libMPI -Duse_netCDF -Dtest_mpp -fltconsistency -stack_temps -safe_cray_ptr -ftz -i_dynamic -assume byterecl -g -O0 -i4 -r8 -override_limits -w95 -traceback
#  LDFLAGS  = -L/lustre/applications/netcdf/netcdf-3.6.3/lib -lnetcdf -lmpi -lsma
  LDFLAGS  = -L/lustre/applications/netcdf/netcdf-3.6.3/lib -lnetcdf -lmpi 
  CFLAGS = -D__IFC
EOF
cp ../$FORT_FILE .
$MKMF -m Makefile -p a.out -t template -x $FORT_FILE $FMS_UTILITIES  $FMS_UTILS/mpp/include

set BOMB = 0

#mpiexec_mpt -np $NPES  ./a.out 
mpirun -np $NPES a.out > results || set BOMB = 1
cp results $OUTPUT_PATH


exit

