#! /bin/csh -f
set echo on
# 05/10/10..For tutorial purposes..using shared code from FMS-SWM
cd /lustre1/scratch/swathi/for_iitm

set OUTPUT_PATH = /lustre1/scratch/swathi/for_iitm # change this to where you want the output to go
set MPPNCCOMBINE = /lustre1/scratch/swathi/shallow_water_zhi_nansen/shallow_water/bin/mppnccombine.ice #  
set NPES = 4 # Try this on more number of PE's
set WORKDIR = $OUTPUT_PATH/tempdir_debug_swm_new
set FMS_UTILS = /lustre1/scratch/swathi/shallow_water_zhi_nansen/shallow_water/src/shared # Change this to where you have the shared FMS code 
#set FMS_UTILITIES = "$FMS_UTILS/utilities $FMS_UTILS/time_manager $FMS_UTILS/mpp $FMS_UTILS/diag_manager $FMS_UTILS/fpe $FMS_UTILS/clocks $FMS_UTILS/memutils"
set FMS_UTILITIES = "$FMS_UTILS/platform $FMS_UTILS/constants $FMS_UTILS/fms $FMS_UTILS/time_manager $FMS_UTILS/mpp $FMS_UTILS/diag_manager  $FMS_UTILS/memutils"
set MKMF         = /lustre1/scratch/swathi/shallow_water_zhi_nansen/shallow_water/bin/mkmf 
set FORT_FILE = heat_eqn_swm_mpp.F90
cd $WORKDIR
/bin/rm *.nc 
# Change what follows to your system template.
cat > template <<EOF
  FC       = ifort -what
  LD       = ifort
  FFLAGS =  -I/usr/local/include -I/lustre/applications/netcdf/netcdf-3.6.3/include -Duse_libMPI -Duse_netCDF -fltconsistency -stack_temps -safe_cray_ptr -ftz -i_dynamic -assume byterecl -g -O0 -i4 -r8 -override_limits -w95 -traceback
  LDFLAGS  = -L/lustre/applications/netcdf/netcdf-3.6.3/lib -lnetcdf -lmpi 
  CFLAGS = -D__IFC
EOF
cp ../$FORT_FILE .
$MKMF -m Makefile -p a.out -t template -x $FORT_FILE $FMS_UTILITIES  $FMS_UTILS/mpp/include

set BOMB = 0
cp ../heat_eqn_nml .

#mpiexec_mpt -np $NPES -tv ./a.out 
totalview mpirun -a  -np $NPES ./a.out > results || set BOMB = 1
cp results $OUTPUT_PATH

if ($BOMB == 0) then
 set diag_list = (`/bin/ls *.nc.0000`)    
 echo "diag_list=" $diag_list
 foreach file ($diag_list)
   set file_nam = $file:r
   $MPPNCCOMBINE  $file_nam
   mv $file_nam $OUTPUT_PATH
   /bin/rm $file_nam* 
 end
endif

exit

