#!/bin/tcsh -f
#PBS -V
#PBS -l walltime=1:00:00
#PBS -l select=2:ncpus=2:mpiprocs=2
#PBS -o run_batch.log
#PBS -j oe
# Minimal runscript: mom4_test1
  limit stacksize 20000000
  source /usr/share/Modules/init/tcsh
  module load intel-cluster-studio-2013
  module load netcdf-4.1.2
  module list
  cd /scratch/swathi/shallow_water_zhi_nansen/shallow_water/scripts
  set echo
  set platform      = hpcs_hp                         # A unique identifier for your platform
  set name          = shallow_water                   # Name of the experiment
  set npes          = 4                               # number of processors
  set days          = 1                            # number of days to run
  set months        = 0                               # number of months to run
  set expdir        = $cwd:h                          # directory of the experiment
  set code_dir      = $expdir/src                     # source code directory
  set preprocessing = $expdir/preprocessing_tsunami   # Preprocessing directory
  set workdir       = $expdir/workdir_tsunami_linear_${platform}    # where the model is run and model output is produced
  set executable    = $expdir/exec_$platform/fms_$name.x        # executable created after compilation
  set diagtable     = $expdir/input/diag_table        # path to diagnositics table
  set bindir        = $expdir/bin                     # path to executalbes.
  set mppnccombine  = $bindir/mppnccombine.$platform  # path to executable mppnccombine
  set time_stamp    = $bindir/time_stamp.csh          # path to cshell to generate the date
  set mkmfTemplate  = $bindir/mkmf.template.$platform # path to template for your platform
  set mkmf          = $bindir/mkmf                    # path to executable mkmf
  set pathnames     = $code_dir/path_names            # path to file containing list of source paths
  set cppDefs       = ( "-Duse_netCDF -Duse_libMPI" ) # list of cpp #defines to be passed to the source files
  if($npes == 1) set cppDefs  = ( "-Duse_netCDF" )  

#--------------------------------------------------------------------------------------------------------
# compile mppnccombine.c, needed only if $npes > 1
  if ( $npes > 1 && ! -f $mppnccombine ) then
    cc -O -o $mppnccombine -I/usr/local/include -I/application/netcdf/netcdf-3.6.3/include -L/application/netcdf-3.6.3/netcdf/lib $code_dir/postprocessing/mppnccombine.c -lnetcdf
  endif

#--------------------------------------------------------------------------------------------------------
# setup directory structure
  if ( ! -d $executable:h )    mkdir  $executable:h
  if ( ! -d $workdir )         mkdir  $workdir
  if ( ! -d $workdir/INPUT )   mkdir  $workdir/INPUT
  if ( ! -d $workdir/RESTART ) mkdir  $workdir/RESTART
#--------------------------------------------------------------------------------------------------------
# compile the model code and create executable
  cd $executable:h
  $mkmf -f -a $code_dir -t $mkmfTemplate -p $executable:t -c "$cppDefs" $pathnames $code_dir/shared/mpp/include /usr/local/include

  make -f Makefile
  exit
#--------------------------------------------------------------------------------------------------------

  unset echo

















